# Generated by Django 3.2.25 on 2024-09-21 12:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('pages', '0024_auto_20240921_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_title',
            field=models.CharField(default='DENT I DELIL CLINIC', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_items',
            field=wagtail.core.fields.StreamField([('portfolio_item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='background_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_description',
            field=models.TextField(default='Your smile, our priority. Affordable dental care abroad.'),
        ),
    ]
