# Generated by Django 3.2.25 on 2024-09-26 03:19

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20240921_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='button_text',
            field=models.CharField(max_length=150, null=True, verbose_name='Button Text'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='body',
            field=wagtail.core.fields.RichTextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='summary',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='faqspage',
            name='body',
            field=wagtail.core.fields.StreamField([('faq_question', wagtail.core.blocks.CharBlock(form_classname='full title', label='FAQ Question')), ('faq_answer', wagtail.core.blocks.RichTextBlock(label='FAQ Answer'))]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_description',
            field=models.TextField(default='Your smile, our priority. Affordable dental care abroad.', verbose_name='Main Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_title',
            field=models.CharField(default='DENT I DELIL CLINIC', max_length=255, verbose_name='Main Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='portfolio_items',
            field=wagtail.core.fields.StreamField([('portfolio_item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title', required=True)), ('subtitle', wagtail.core.blocks.CharBlock(label='Subtitle', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image', required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontentitem',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='homepagecontentitem',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='homepagecontentitem',
            name='summary',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='homepagecontentitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='site_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Your Facebook page URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook_appid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Your Facebook AppID'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='github',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Your Github URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Your Instagram URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Your Linkedin URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Your Twitter URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Your YouTube Channel URL'),
        ),
        migrations.AlterField(
            model_name='standardindexpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='standardindexpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraph')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('html', wagtail.core.blocks.RawHTMLBlock(label='HTML'))]),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='testimonialpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='videogallerypage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Intro'),
        ),
    ]
