# Generated by Django 3.2.25 on 2024-09-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180607_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIContentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prompt_template', models.TextField(help_text='Template for AI content generation.')),
            ],
        ),
    ]
